Changed group: hosts to allow inline variable assignment
jhoekx/ansible-yaml-inventory pull request #2
Opened 2016-09-27 07:04 UTC by jamessewell

Hi,

Change to allow the following syntax:

```
- group: <groupname>
  vars:
  - groupvar: value
  hosts:
  - myhost1
  - host: myhost2
    vars:
      myvcr: vclue
  groups:
  - subgroup1
  - subgroup2
```

Standard hosts and dict hosts can be mixed and matched.

2016-09-27 16:00 UTC, jhoekx requested changes
Looks good, thanks. A few details that should probably be fixed though.

2016-09-27 16:00 UTC, jhoekx commented on yaml-hosts.py
> +            print entry
I think we do not really want this print here, no?

2016-09-27 16:00 UTC, jhoekx commented on yaml-hosts.py
> +parser.add_option('-f', '--file', default=os.path.join(base_dir,"hosts.yaml"), dest="yaml_file")
Just for consistency: add a space before the `"hosts.yaml"`.

2016-09-27 20:12 UTC, jamessewell commented
Hi,

Thanks!

So after doing some work I noticed that the format of your --list output
was ... strange.

Maybe this was written for a really old Ansible?

Anyway I'm halfway to supporting the output as defined in the developing
dynamic inventories page, just have to get the _meta stuff working and try
to work out how all is meant to work.

Cheers,
James Sewell

On Wednesday, 28 September 2016, Jeroen Hoekx <notifications@github.com>
wrote:

> *@jhoekx* requested changes on this pull request.
>
> Looks good, thanks. A few details that should probably be fixed though.
> ------------------------------
>
> In yaml-hosts.py
> <https://github.com/jhoekx/ansible-yaml-inventory/pull/2#pullrequestreview-1764251>
> :
>
> > @@ -189,6 +217,7 @@ def parse_yaml(yaml_hosts):
>                  ungrouped.add_host(host)
>
>          elif 'host' in entry:
> +            print entry
>
> I think we do not really want this print here, no?
> ------------------------------
>
> In yaml-hosts.py
> <https://github.com/jhoekx/ansible-yaml-inventory/pull/2#pullrequestreview-1764251>
> :
>
> >  parser = OptionParser()
> +parser.add_option('-f', '--file', default=os.path.join(base_dir,"hosts.yaml"), dest="yaml_file")
>
> Just for consistency: add a space before the "hosts.yaml".
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jhoekx/ansible-yaml-inventory/pull/2#pullrequestreview-1764251>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABKRoxMvoETqzH5lp7b9Z_GPqPC7e7faks5quT2tgaJpZM4KHUmH>
> .
>

2016-09-28 06:01 UTC, jhoekx requested changes
A few small thing I noticed when testing. With these fixed it was working in my example.

2016-09-28 06:01 UTC, jhoekx commented on yaml-hosts.py
> +parser.add_option('-f', '--file', default=os.path.join(base_dir, "hosts.yaml"), dest="yaml_file")
This default extension should be `.yml`

2016-09-28 06:01 UTC, jhoekx commented on yaml-hosts.py
> +                break
I think that this branch should also set the host variable.

2016-09-28 06:03 UTC, jhoekx commented
This was actually part of Ansible proper from version (I'm lying, but you get the idea) 0.3 to 0.6. It was never updated with the 'new' _meta syntax.

2016-09-28 06:27 UTC, jamessewell commented
Ha, I see.

With these new changes it's really helping us to manage our inventory, hopefully it can make it back in!

I've done a bit of cleanup and added a label: tag for a group, which will set a variable with the groupname:

so 

```
group: james
label: name
```

would yield:

 ```
"james": {
        "children": [],
        "hosts": [],
        "vars": {
            "name": "james"
        }
```

2016-09-29 08:56 UTC, jhoekx commented
Could you ping me when you're done making changes? Then I'll review and merge.

2016-09-29 09:12 UTC, jamessewell commented
It's fine now.

I'm not 100% sold on the environment variable logic, but it's what we want
in production.

I'm also not sure on the merge vars behaviour, but once again it's what I
want for us.

Apart from that I'm happy. The import_vars stuff was working, but it seemed
too involved.

Cheers,
James Sewell

On Thursday, 29 September 2016, Jeroen Hoekx <notifications@github.com>
wrote:

> Could you ping me when you're done making changes? Then I'll review and
> merge.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jhoekx/ansible-yaml-inventory/pull/2#issuecomment-250409359>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABKRo8V-n8bhCNvpxsfr1bgX3sx3RyLgks5qu31GgaJpZM4KHUmH>
> .
>

2016-09-29 18:54 UTC, jhoekx approved these changes

2016-09-29 18:55 UTC, merged

2016-09-29 18:56 UTC, jhoekx commented
Merged. Thanks for bringing the yaml inventory in the modern age of ansible!

2016-09-29 21:21 UTC, jamessewell commented
Hi,

Hey I just realised that my email address hasn't been pulling through - I
don't suppose you could update the entries?

If you look in my fork there is a script which does it which I committed
briefly - try.file.

Cheers,
James

On Fri, Sep 30, 2016 at 4:56 AM, Jeroen Hoekx <notifications@github.com>
wrote:

> Merged. Thanks for bringing the yaml inventory in the modern age of
> ansible!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jhoekx/ansible-yaml-inventory/pull/2#issuecomment-250558815>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABKRo6hKqenLd3yQ0IMsbXVxDzxCqJN7ks5qvAnKgaJpZM4KHUmH>
> .
>

2016-09-30 06:50 UTC, jhoekx commented
Ok, changed. I also updated the name in the commits.